### ISSUE TITLE
[game] The amount of players is not extensible

### ISSUE THREAD

**Issue by heyapricot** [rvvergara/tictactoe#12]
Currently, you have two players only. This is hardcoded since you have two variables `@player_one` and `@player_two`. Is there a way to make the game ready for `N` players? This would make it `extensible`

**Comment by rvvergara** [comment]
Thanks. Though I must ask for a clarification. We deliberately limited the design to a two player game as tictactoe (as well as chess, battleship, checkers) is historically and globally a two-player game. Unless what you mean is we should design the app right now to also allow for other types of games later on (games that allow for 2+ players)?

**Comment by rvvergara** [comment]
Issue closed as we already addressed it
